# Generated by Django 3.2.21 on 2023-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
